[platformio]
default_envs = esp32dev

[env:esp32dev]
framework = arduino
platform = espressif32@6.10.0
board = esp32dev
; board_build.partitions = noota_3g.csv  ; Remove if not needed
upload_protocol = esptool
monitor_speed = 115200

lib_deps = 
    SPI
    SPIFFS
    FS
    WiFi
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ESP32Async/AsyncTCP @ 3.3.2
    me-no-dev/AsyncTCP
    FlexyStepper
    AccelStepper
    ESPmDNS
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    ArduinoJson
